name: Tableau Workbook Workflows Staging
on:
  pull_request:
      branches:
        - master
jobs:
  tableau-validation-action:
    name: Tableau Workbook Staging Publisher
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Tableau Workbook Action' #This workflows expected to be error since no secrets vars provided
        uses: ./
        env:
          USERNAME: saad.rehman456@gmail.com
          PASSWORD: ABS@@d123
          SITE_ID: saadpractice
          TABLEAU_URL: https://prod-apsoutheast-a.online.tableau.com/#/site/saadpractice/personalSpace
        with:
          workbook_dir: tests/workbooks
          env: staging
          repo_token: ${{ secrets.GIT_TOKEN }}
